package com.pitstop.models.trip;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pitstop.models.trip.Location;
import com.pitstop.models.trip.Trip;

import com.pitstop.models.trip.LocationDao;
import com.pitstop.models.trip.TripDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig locationDaoConfig;
    private final DaoConfig tripDaoConfig;

    private final LocationDao locationDao;
    private final TripDao tripDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        locationDaoConfig = daoConfigMap.get(LocationDao.class).clone();
        locationDaoConfig.initIdentityScope(type);

        tripDaoConfig = daoConfigMap.get(TripDao.class).clone();
        tripDaoConfig.initIdentityScope(type);

        locationDao = new LocationDao(locationDaoConfig, this);
        tripDao = new TripDao(tripDaoConfig, this);

        registerDao(Location.class, locationDao);
        registerDao(Trip.class, tripDao);
    }
    
    public void clear() {
        locationDaoConfig.clearIdentityScope();
        tripDaoConfig.clearIdentityScope();
    }

    public LocationDao getLocationDao() {
        return locationDao;
    }

    public TripDao getTripDao() {
        return tripDao;
    }

}
